Add Auth, Private Route & Validations
LauraCanon/React-proyecto pull request #17
Opened 2021-12-10 15:46 UTC by AndresXLP

2021-12-10 16:16 UTC, mhbuiles requested changes

2021-12-10 16:16 UTC, mhbuiles commented on src/navbar.jsx
> +                      Usuario x logueado
Asumo que esto es temporal?

2021-12-10 16:16 UTC, mhbuiles commented on src/navbar.jsx
> +                      Registrare
Aquí tenemos un typo, asumo que es: Regístrate

2021-12-10 16:16 UTC, mhbuiles commented on src/views/HomeCollabolator.jsx
>                      <div className="card-body">
Creo que no veo el prop key en el elemento que retorna el .map

2021-12-10 16:16 UTC, mhbuiles commented on src/views/SessionLogin.jsx
> +  console.log(isAuth);
Necesitamos este console.log??

2021-12-10 21:30 UTC, AndresXLP commented on src/navbar.jsx
> +                      Usuario x logueado
Si es temporal mientras se hacen los llamados a la API

2021-12-10 21:40 UTC, AndresXLP commented on src/navbar.jsx
> +                      Registrare
Listo ya se realizo el cambio en otro commit

2021-12-10 21:40 UTC, AndresXLP commented on src/views/HomeCollabolator.jsx
>                      <div className="card-body">
Listo se agrego la key

2021-12-10 21:40 UTC, AndresXLP commented on src/views/SessionLogin.jsx
> +  console.log(isAuth);
Si ex cierto, se elimino esa linea

2021-12-11 07:36 UTC, mhbuiles approved these changes

2021-12-12 00:14 UTC, merged